DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS pedido CASCADE;
DROP TABLE IF EXISTS produto CASCADE;
DROP TABLE IF EXISTS endereco CASCADE;
DROP TABLE IF EXISTS empresa CASCADE;

CREATE TABLE IF NOT EXISTS usuario (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(15) NOT NULL UNIQUE,
	email VARCHAR(255) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL,
	data_nascimento DATE,
	foto_perfil VARCHAR(255),
	CONSTRAINT usuario_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS empresa (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL,
    foto_perfil VARCHAR(255) NOT NULL,
    telefone VARCHAR(15),
    cep VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    bairro VARCHAR(255) NOT NULL,
    rua VARCHAR(255) NOT NULL,
    numero INT NOT NULL,
    complemento VARCHAR(255),
	CONSTRAINT empresa_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS endereco (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cep VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    bairro VARCHAR(255) NOT NULL,
    rua VARCHAR(255) NOT NULL,
    numero INT NOT NULL,
    complemento VARCHAR(255),
    usuario_id BIGINT NULL,
	CONSTRAINT endereco_id PRIMARY KEY (id),
    CONSTRAINT endereco_id_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE IF NOT EXISTS produto (
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    foto VARCHAR (255) NOT NULL,
    preco FLOAT NOT NULL,
    empresa_id BIGINT NULL,
	CONSTRAINT produto_id PRIMARY KEY (id),
    CONSTRAINT produto_id_empresa FOREIGN KEY (empresa_id) REFERENCES empresa(id)
);

insert into usuario (nome, cpf, email, senha, data_nascimento, foto_perfil)
values ('Maria Luiza','12332112332', 'malu@gmail.com', '1234', '2002-10-14', 'https://www.macetesdemae.com/wp-content/uploads/2022/06/mulher-695x600.png');

insert into empresa (nome, cnpj, senha, foto_perfil, telefone, cep, cidade, bairro, rua, numero, complemento)
values ('Pizzaria','123332123436', '1234', 'https://diariodorio.com/wp-content/uploads/2020/07/daleopizzaria_20200710_144435_0.jpg', '83997688765', '58900000', 'Cajazeiras', 'Centro', 'Francisco de Albuquerque', 76, 'Ao lado da Praça João Pessoa');

insert into endereco (cep, cidade, bairro, rua, numero, complemento, usuario_id)
values ('58900-000','Cajazeiras', 'Estrada do Amor', 'João Oliveira Júnior', 434, 'Perto da RC', 1);

insert into produto (nome, foto, preco, empresa_id)
values ('Pizza G','https://soubh.uai.com.br/uploads/post/image/9034/main_150705_pizza_2.jpg', 55.60, 1);
